### ISSUE TITLE
Consider PR'ing to the cml-community

### ISSUE THREAD

**Issue by xorrkaz** [thepurplebuffalo/OpenBSD-CML#1]
Thanks for doing the OpenBSD node def!  Being a FreeBSD committer myself, I respect the BSD users of the world.  This isn't a real issue with your work per se, but would you consider doing a PR to https://github.com/ciscodevnet/cml-community so we can consolidate the node def efforts so more people can benefit from your great work?

**Comment by rschmied** [comment]
we can also link this as a sub-project.  As @xorrkaz said, the consolidation piece is the important bit.

**Comment by thepurplebuffalo** [comment]
I can submit a PR for the OpenBSD portion as soon as I have a few spare minutes.  I'll update it to OpenBSD 7.6 at the same time.

As for FreeBSD I'll want to do the testing in my lab before I commit to anything.

**Comment by xorrkaz** [comment]
Thanks!  And if you _want_ to do a FreeBSD node def, fantastic!  I had that deep on my own TODO list.

**Comment by thepurplebuffalo** [comment]
All done.
